Equipo
Integrantes:
- Carla Sophia Rodríguez Dander - A01781793
- Isaac Husny - A01027140
- Jesus Rodríguez - A01025112

##Librerías

In [ ]:
! pip install category_encoders

Requirement already satisfied: category_encoders in /usr/local/lib/python3.10/dist-packages (2.6.3)
Requirement already satisfied: numpy>=1.14.0 in /usr/local/lib/python3.10/dist-packages (from category_encoders) (1.23.5)
Requirement already satisfied: scikit-learn>=0.20.0 in /usr/local/lib/python3.10/dist-packages (from category_encoders) (1.3.2)
Requirement already satisfied: scipy>=1.0.0 in /usr/local/lib/python3.10/dist-packages (from category_encoders) (1.11.3)
Requirement already satisfied: statsmodels>=0.9.0 in /usr/local/lib/python3.10/dist-packages (from category_encoders) (0.14.0)
Requirement already satisfied: pandas>=1.0.5 in /usr/local/lib/python3.10/dist-packages (from category_encoders) (1.5.3)
Requirement already satisfied: patsy>=0.5.1 in /usr/local/lib/python3.10/dist-packages (from category_encoders) (0.5.3)
Requirement already satisfied: python-dateutil>=2.8.1 in /usr/local/lib/python3.10/dist-packages (from pandas>=1.0.5->category_encoders) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas>=1.0.5->category_encoders) (2023.3.post1)
Requirement already satisfied: six in /usr/local/lib/python3.10/dist-packages (from patsy>=0.5.1->category_encoders) (1.16.0)
Requirement already satisfied: joblib>=1.1.1 in /usr/local/lib/python3.10/dist-packages (from scikit-learn>=0.20.0->category_encoders) (1.3.2)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from scikit-learn>=0.20.0->category_encoders) (3.2.0)
Requirement already satisfied: packaging>=21.3 in /usr/local/lib/python3.10/dist-packages (from statsmodels>=0.9.0->category_encoders) (23.2)

In [ ]:
from google.colab import drive
import pandas as pd
import numpy as np

In [ ]:
#from category_encoders import TargetEncoder
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, precision_score, recall_score

##Carga de CSV

In [ ]:
drive.mount('/content/drive')
path='/content/drive/Shareddrives/COLAB DATOS DE LIVERPOOL/Datos Liverpool/'
Historico=pd.read_csv(path+'HistoricoLimpio.csv')
Demo=pd.read_csv(path+'DemoLimpio.csv')

Mounted at /content/drive

In [ ]:
pd.options.display.max_columns = None
display(Historico.head(n=2))
display(Demo.head(n=2))

,Nº pers.,Fecha Salida,HAño,HMes,Desde,DAño,DMes,Duracion,Desc Soc,Locación,GroPer,Área Personal,Departamento,Unidad,Desc Función,Duración Días
0,3369,1999-12-31,1999,12,1999-01-01,1999,1,0.997260,Servicios Liverpool S.A.,Servicios Liverpool,Planta No Sind.,Ejecutivo/ Coord.,JUNIORS,Compras Juniors,Comprador Sr B,364
1,3369,2004-01-31,2004,1,2000-01-01,2000,1,4.084932,Servicios Liverpool S.A.,Servicios Liverpool,Planta No Sind.,Ejecutivo/ Coord.,JUNIORS,Compras Juniors,Comprador Sr B,1491

,Nº pers.,Fecha nacimiento,Genero,No Hijos,Fecha ingreso,IAño,IMes,Edad ingreso,Fecha Salida,SAño,SMes,Duracion,Antigüedad,Edad salida,Año salida,Desc Medida,Ultima Evaluación,CP Vivienda,CP Trabajo,Locación,Desc Fun,GroPer,Área Personal,Departamento,Unidad,Duración Días,Duración Meses,Duración Trimestres
0,15212625,2000-07-20,Hombre,0,2019-11-27,2019,11,19,2022-08-18,2022,8,2.726027,2,22,2022,Baja,3.12,1000,1140,CeDis Regional Tacubaya,Personal Operativo,Planta No Sind.,Personal General,ENVIOS,Supervision Recepcion CD,995,33,11
1,15472429,1978-12-21,Hombre,0,2021-04-28,2021,4,42,2022-03-01,2022,3,0.841096,0,43,2022,Baja,3.00,1000,1140,CeDis Regional Tacubaya,Recepcion Mercancia,Eventual No Sind.,Personal General,PAQUETERIA,Jefatura Paqueteria I CD,307,11,4

##Target Encoding (''Antigüedad en Grupos'')

In [ ]:
#target encoding para la columna 'GroPer'
encoder1 = TargetEncoder(cols = ['GroPer'], smoothing=0)

# Fit and transform the encoder on your dataset
Demo['GroPer_TE'] = encoder1.fit_transform(Demo['GroPer'], Demo['Antigüedad_Grupos'])

In [ ]:
#target encoding para la columna 'Departamento'
encoder2 = TargetEncoder(cols = ['Departamento'], smoothing=0)

# Fit and transform the encoder on your dataset
Demo['Departamento_TE'] = encoder2.fit_transform(Demo['Departamento'], Demo['Antigüedad_Grupos'])

In [ ]:
#target encoding para la columna 'Desc Fun'
encoder3 = TargetEncoder(cols = ['Desc Fun'], smoothing=0)

# Fit and transform the encoder on your dataset
Demo['Función_TE'] = encoder3.fit_transform(Demo['Desc Fun'], Demo['Antigüedad_Grupos'])

In [ ]:
#target encoding para la columna 'Locación'
encoder4 = TargetEncoder(cols = ['Locación'], smoothing=0)

# Fit and transform the encoder on your dataset
Demo['Locación_TE'] = encoder4.fit_transform(Demo['Locación'], Demo['Antigüedad_Grupos'])

In [ ]:
#target encoding para la columna 'Locación'
encoder5 = TargetEncoder(cols = ['Área Personal'], smoothing=0)

# Fit and transform the encoder on your dataset
Demo['Área_Personal_TE'] = encoder5.fit_transform(Demo['Área Personal'], Demo['Antigüedad_Grupos'])

In [ ]:
#target encoding para la columna 'Locación'
encoder6 = TargetEncoder(cols = ['Desc Soc'], smoothing=0)

# Fit and transform the encoder on your dataset
Demo['Desc_Soc_TE'] = encoder6.fit_transform(Demo['Desc Soc'], Demo['Antigüedad_Grupos'])

##Drop de columnas que no vamos a utilizar

In [ ]:
columns_to_drop = ['Ultima Evaluación', 'CP Vivienda', 'NDia', 'IAño', 'Duracion', 'GroPer', 'CP Trabajo', 'Nº pers.', 'Fecha nacimiento', 'Fecha ingreso', 'Antigüedad', 'Fecha Salida', 'Unidad', 'Desc Soc', 'Año salida', 'Unidad', 'Departamento', 'Locación', 'Desc Fun', 'Área Personal', 'Desc Medida', 'Genero', 'SAño', 'Edad salida','SMes', 'Duración Días']
Dataset_2 = Demo.drop(columns=columns_to_drop)
Dataset_2 = Dataset_2.dropna()        # Drop all rows with NaN values
Dataset_2 = Dataset_2.reset_index(drop=True)
Dataset_2

,NAño,NMes,No Hijos,IMes,Edad ingreso,Antigüedad_Grupos,GroPer_TE,Departamento_TE,Función_TE,Locación_TE,Área_Personal_TE,Desc_Soc_TE
0,1997,3,0,6,18,2,0.703896,0.765256,0.706913,0.847862,0.696924,0.732517
1,1991,5,0,2,27,1,0.988776,1.153992,1.000000,0.847862,0.979834,0.921090
2,1992,3,2,12,27,1,0.605447,1.153992,1.170040,0.847862,0.758548,0.921090
3,1970,3,0,9,42,2,0.988776,1.153992,1.000000,0.847862,0.979834,0.877903
4,1965,1,0,5,53,1,0.988776,1.153992,1.170040,0.847862,0.758548,0.921090
...,...,...,...,...,...,...,...,...,...,...,...,...
61099,1996,7,0,4,21,1,0.988776,0.903794,0.811570,0.847862,0.841567,0.789346
61100,1996,1,0,6,22,0,0.988776,0.903794,0.811570,0.750000,0.841567,0.789346
61101,1990,8,0,1,28,0,0.988776,0.903794,0.811570,0.847862,0.979834,0.789346
61102,1998,5,0,9,21,0,0.988776,0.903794,0.811570,0.847862,0.841567,0.789346
61103,1996,1,0,9,23,0,0.988776,0.903794,0.811570,0.847862,0.841567,0.789346

##Modelado

###Regresión Logística Multinomial ('Antigüedad en Grupos')

In [ ]:
X = Dataset_2.drop(columns=['Antigüedad_Grupos'], axis=1)
y = Dataset_2['Antigüedad_Grupos']

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [ ]:
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [ ]:
# Create and train the multinomial logistic regression model
clf_LR = LogisticRegression(multi_class='multinomial', solver='lbfgs')
clf_LR.fit(X_train_scaled, y_train)

LogisticRegression(multi_class='multinomial')

In [ ]:
# Make predictions on the test set
y_pred = clf_LR.predict(X_test_scaled)

In [ ]:
# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
print(f'Accuracy: {accuracy:.2f}')

Accuracy: 0.78

In [ ]:
precision = precision_score(y_test, y_pred, average='weighted')
recall = recall_score(y_test, y_pred, average='weighted')

# Print the results
print(f'Precision: {precision:.4f}')
print(f'Recall: {recall:.4f}')

Precision: 0.7753
Recall: 0.7772

###Random Forest ('Antigüedad en Grupos')

In [ ]:
X = Dataset_2.drop(columns=['Antigüedad_Grupos'], axis=1)
y = Dataset_2['Antigüedad_Grupos']

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [ ]:
clf_RF = RandomForestClassifier(n_estimators=70, random_state=42)  # You can adjust hyperparameters as needed
clf_RF.fit(X_train, y_train)

RandomForestClassifier(n_estimators=70, random_state=42)

In [ ]:
y_pred = clf_RF.predict(X_test)

In [ ]:
accuracy = accuracy_score(y_test, y_pred)
print(f'Accuracy: {accuracy:.2f}')

Accuracy: 0.78

In [ ]:
precision = precision_score(y_test, y_pred, average='weighted')
recall = recall_score(y_test, y_pred, average='weighted')

# Print the results
print(f'Precision: {precision:.4f}')
print(f'Recall: {recall:.4f}')

Precision: 0.7848
Recall: 0.7843

###Guardado de los Modelos

In [ ]:
import joblib

In [ ]:
# Save the model to a file using joblib
joblib.dump(clf_RF, 'RandomForest_clf.joblib')

['RandomForest_clf.joblib']

In [ ]:
# Save the scaler using joblib
joblib.dump(scaler, 'standard_scaler.joblib')

['standard_scaler.joblib']

In [ ]:
joblib.dump(clf_LR, 'LogisticRegression_clf.joblib')

['LogisticRegression_clf.joblib']

In [ ]:
# Save the target encoder using joblib
joblib.dump(encoder1, 'target_encoder_GroPer.joblib')

['target_encoder_GroPer.joblib']

In [ ]:
joblib.dump(encoder2, 'target_encoder_Departamento.joblib')

['target_encoder_Departamento.joblib']

In [ ]:
joblib.dump(encoder3, 'target_encoder_Funcion.joblib')

['target_encoder_Funcion.joblib']

In [ ]:
joblib.dump(encoder4, 'target_encoder_Locacion.joblib')

['target_encoder_Locacion.joblib']

In [ ]:
joblib.dump(encoder5, 'target_encoder_Area_Personal.joblib')

['target_encoder_Area_Personal.joblib']

In [ ]:
joblib.dump(encoder6, 'target_encoder_Desc_Soc.joblib')

['target_encoder_Desc_Soc.joblib']